'use strict';
// Deterministic worker bundle: WeChat workers may only require files inside workers/.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const modules = new Map();
function visit(file) {
  const absolute = path.resolve(root, file);
  const relative = path.relative(root, absolute).split(path.sep).join('/');
  if (relative.startsWith('../') || path.isAbsolute(relative)) throw Error('Dependency escapes repository');
  if (modules.has(relative)) return relative;
  const source = fs.readFileSync(absolute, 'utf8').replace(/\r\n/g, '\n');
  const dependencies = {};
  modules.set(relative, { source, dependencies });
  for (const match of source.matchAll(/require\(['"]([^'"]+)['"]\)/g)) {
    const specifier = match[1];
    if (!specifier.startsWith('.')) throw Error('Worker has external dependency: ' + specifier);
    const target = path.resolve(path.dirname(absolute), specifier + (path.extname(specifier) ? '' : '.js'));
    dependencies[specifier] = visit(target);
  }
  return relative;
}
const entry = visit('utils/phonetic/analysis.js');
const config = visit('utils/phonetic/phonetic-config.js');
const definitions = [...modules].sort(([a],[b])=>a.localeCompare(b,'en')).map(([file, item]) =>
  JSON.stringify(file) + ': [function(require,module,exports){\n' + item.source + '\n},' + JSON.stringify(item.dependencies) + ']');
const digest = crypto.createHash('sha256');
for (const [file, item] of [...modules].sort(([a],[b])=>a.localeCompare(b,'en'))) digest.update(file+'\n'+item.source);
const content = '// Generated by node scripts/build-worker.cjs; source SHA-256 '+digest.digest('hex')+'\n'
  + '(function(){\nconst definitions={\n'+definitions.join(',\n')+'\n};\n'
  + 'const cache={}; function load(id){ if(cache[id])return cache[id].exports; const definition=definitions[id];'
  + 'if(!definition)throw new Error("Unknown worker module: "+id); const module={exports:{}};cache[id]=module;'
  + 'definition[0](name=>load(definition[1][name]),module,module.exports);return module.exports;}\n'
  + 'module.exports={...load('+JSON.stringify(entry)+'),...load('+JSON.stringify(config)+')};\n})();\n';
const output = path.join(root,'workers/phonetic-analysis/bundle.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(output) || fs.readFileSync(output,'utf8').replace(/\r\n/g,'\n') !== content) {
    throw Error('Worker bundle is stale; run node scripts/build-worker.cjs');
  }
  console.log('Worker bundle matches '+modules.size+' source modules.');
} else {
  fs.writeFileSync(output,content);
  console.log('Built '+modules.size+' modules ('+Buffer.byteLength(content)+' bytes).');
}
